<a href="https://colab.research.google.com/github/madhukar1996/Practice_DL/blob/master/Pytorch_practice/Pytorch_Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# just adding something
import torch
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
x=torch.ones(3,2)
print(x)
x=torch.zeros(3,3)
print(x)
x=torch.rand(2,2)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.2405, 0.9256],
        [0.8102, 0.9973]])


In [ ]:
x=torch.empty(3,2)
print(x)
x=torch.zeros_like(x)
print(x)

tensor([[3.3650e+31, 3.0663e-41],
        [3.3631e-44, 0.0000e+00],
        [       nan, 1.0000e+00]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [ ]:
x=torch.ones(2,2)
y=torch.ones(2,2)

In [ ]:
z=x+y
print(z)
z=x-y
print(z)
z=x*y
print(z)

tensor([[2., 2.],
        [2., 2.]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])


In [ ]:
# Normal adding
z=y.add(x)
print(z)
print(y)
# Inplace adding
z=y.add_(x)
print(z)
print(y)

tensor([[2., 2.],
        [2., 2.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.]])


In [ ]:
# Numpy and torch conversion

In [ ]:
xnp=x.numpy()
print(type(x),type(xnp))
print(xnp)

<class 'torch.Tensor'> <class 'numpy.ndarray'>
[[1. 1.]
 [1. 1.]]


In [ ]:
b=torch.from_numpy(xnp)
print(type(b),type(xnp))
print(b)

<class 'torch.Tensor'> <class 'numpy.ndarray'>
tensor([[1., 1.],
        [1., 1.]])


In [ ]:
# Same memory used when torch.from_numpy() It is actually a bridge
np.add(xnp,1,out=xnp)
print(xnp)
print(b)

[[2. 2.]
 [2. 2.]]
tensor([[2., 2.],
        [2., 2.]])


In [ ]:
# NFS (Need For Speed)

In [ ]:
%%time
for i in range(10):
  a=np.random.randn(10000,10000)
  b=np.random.randn(10000,10000)
  c=a+b

CPU times: user 1min 24s, sys: 1.22 s, total: 1min 26s
Wall time: 1min 25s


In [ ]:
%%time
for i in range(10):
  a=torch.randn([10000,10000])
  b=torch.randn([10000,10000])
  c=a+b

CPU times: user 21.5 s, sys: 33.7 ms, total: 21.5 s
Wall time: 21.5 s


In [ ]:
# using CUDA

In [ ]:
print(torch.cuda.device_count())

1


In [ ]:
print(torch.cuda.device(0))

In [ ]:
cuda0 = torch.device('cuda:0')

In [ ]:
%%time
for i in range(10):
  a=np.random.randn(10000,10000)
  b=np.random.randn(10000,10000)
  np.add(a,b)

CPU times: user 1min 11s, sys: 334 ms, total: 1min 12s
Wall time: 1min 11s


In [ ]:
%%time
for i in range(10):
  a=torch.randn([10000,10000])
  b=torch.randn([10000,10000])
  # inplace addition
  b.add_(a)

CPU times: user 17.8 s, sys: 14.8 ms, total: 17.8 s
Wall time: 17.7 s


In [ ]:
%%time
for i in range(10):
  a=torch.randn([10000,10000],device=cuda0)
  b=torch.randn([10000,10000],device=cuda0)
  b.add_(a)

CPU times: user 1.69 ms, sys: 0 ns, total: 1.69 ms
Wall time: 1.38 ms


In [ ]:
# AutoGrad

In [ ]:
x= torch.ones(3,2,requires_grad=True)
y=x+3
r=(1/(1+torch.exp(-y)))
a=torch.ones(3,2)
r.backward(a)
x.grad

tensor([[0.0177, 0.0177],
        [0.0177, 0.0177],
        [0.0177, 0.0177]])

tensor([[0.0177, 0.0177],
        [0.0177, 0.0177],
        [0.0177, 0.0177]])

In [ ]:
# autograd example for linear reg

In [ ]:
x=torch.randn(20,1)
y=3*x-2
w=torch.tensor([1.],requires_grad=True)
b=torch.tensor([1.],requires_grad=True)
yhat= w*x+b
loss=torch.sum((y-yhat)**2)
print(loss)
loss.backward()
print(w.grad,b.grad)

tensor(265.1402, grad_fn=<SumBackward0>)
tensor([-105.1433]) tensor([106.6646])
