<a href="https://colab.research.google.com/github/madhukar1996/Practice_DL/blob/master/Pytorch_Intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import torch
import numpy as np
import matplotlib.pyplot as plt

In [2]:
x=torch.ones(3,2)
print(x)
x=torch.zeros(3,3)
print(x)
x=torch.rand(2,2)
print(x)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.8265, 0.8031],
        [0.7624, 0.5874]])


In [3]:
x=torch.empty(3,2)
print(x)
x=torch.zeros_like(x)
print(x)

tensor([[2.5109e-11, 3.0943e-41],
        [3.3631e-44, 0.0000e+00],
        [       nan, 0.0000e+00]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])


In [8]:
x=torch.ones(2,2)
y=torch.ones(2,2)

In [9]:
z=x+y
print(z)
z=x-y
print(z)
z=x*y
print(z)

tensor([[2., 2.],
        [2., 2.]])
tensor([[0., 0.],
        [0., 0.]])
tensor([[1., 1.],
        [1., 1.]])


In [10]:
# Normal adding
z=y.add(x)
print(z)
print(y)
# Inplace adding
z=y.add_(x)
print(z)
print(y)

tensor([[2., 2.],
        [2., 2.]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.]])


In [11]:
# Numpy and torch conversion

In [12]:
xnp=x.numpy()
print(type(x),type(xnp))
print(xnp)

<class 'torch.Tensor'> <class 'numpy.ndarray'>
[[1. 1.]
 [1. 1.]]


In [13]:
b=torch.from_numpy(xnp)
print(type(b),type(xnp))
print(b)

<class 'torch.Tensor'> <class 'numpy.ndarray'>
tensor([[1., 1.],
        [1., 1.]])


In [15]:
# Same memory used when torch.from_numpy() It is actually a bridge
np.add(xnp,1,out=xnp)
print(xnp)
print(b)

[[3. 3.]
 [3. 3.]]
tensor([[3., 3.],
        [3., 3.]])


In [17]:
# NFS (Need For Speed)

In [20]:
%%time
for i in range(10):
  a=np.random.randn(10000,10000)
  b=np.random.randn(10000,10000)
  c=a+b

CPU times: user 1min 23s, sys: 808 ms, total: 1min 24s
Wall time: 1min 23s


In [26]:
%%time
for i in range(10):
  a=torch.randn([10000,10000])
  b=torch.randn([10000,10000])
  c=a+b

CPU times: user 20.8 s, sys: 19.7 ms, total: 20.8 s
Wall time: 20.7 s
